### ISSUE TITLE
What do I have to do to run the iOS app for this project

### ISSUE THREAD

**Issue by DiamoandDog** [thingsboard/flutter_thingsboard_app#1]
I want run this app,and first I execute pod install ,but it gave an error,like this:
[
![截屏2021-07-21 下午5 35 05](https://user-images.githubusercontent.com/14171367/126468421-fa14a8d8-0634-49f6-8eb0-8a34913a5b30.png)
](url)

**Comment by vvlladd28** [comment]
Hi @DiamoandDog,
Run iOS project your need Mac OS and Xcode.
