### ISSUE TITLE
Error with 

### ISSUE THREAD

**Issue by PhilipRai** [thingsboard/flutter_thingsboard_app#105]
Trying to get project to load:

`Changing current working directory to: /Users/philipraistrick/flutter_thingsboard_app-dev
"ar": 3 untranslated message(s).
"zh": 22 untranslated message(s).
"zh_CN": 22 untranslated message(s).
"zh_TW": 21 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 

This will generate a JSON format file containing all messages that 
need to be translated.
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...                                           1.170ms
Running Xcode build...                                                  
Xcode build done.                                           31,9s
Failed to build iOS app
Error (Xcode): lib/modules/alarm/presentation/bloc/alarm_types/alarm_types_bloc.dart:15:40: Error: Type 'AlarmType' not found.

Could not build the application for the simulator.
Error launching application on iPhone 13.
philipraistrick@MBPtilhdePhilip ios % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale da-DK)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
`

**Comment by ybeshkarov** [comment]
It's because you use the dev branch. Use `master` or `release/1.2.0` instead. Flutter 3.19.6.

**Comment by PhilipRai** [comment]
Doesnt master and 1.2.0 require Dart 3.4.0?

**Comment by ybeshkarov** [comment]
Flutter 3.19.6 uses the Dart 3.3.4 version.

**Comment by PhilipRai** [comment]
Reinstalled the version (Master) because the dependency versions was way off the original. 

Did a `flutter update-packages --force-upgrade` to fix the flutter_localization and intl. 

Now im stuck at:

`Error (Xcode): lib/modules/dashboard/dashboard.dart:161:35: Error: The argument type 'Uri' can't be assigned to the parameter
type 'WebUri?'.`

**Comment by ybeshkarov** [comment]
You need to use Flutter 3.19.6 and don't change any dependencies version in `pubspec.yaml`.

**Comment by PhilipRai** [comment]
But then there's this:

`Because every version of flutter_localizations from sdk depends on intl 0.19.0 and thingsboard_app depends on intl ^0.18.1,
  flutter_localizations from sdk is forbidden.
So, because thingsboard_app depends on flutter_localizations from sdk, version solving failed.`

**Comment by ybeshkarov** [comment]
Make sure when you run the `flutter --version` command in your terminal you will find the next output
```Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (4 months ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1
```

Then don't change any dependencies you will be able to build a project with `flutter run` or through the IDE you working with.

**Comment by PhilipRai** [comment]
Ah. I think is wrong with my `fvm`. 

`flutter --version` creates this:
'Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (3 weeks ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3'



and 'fvm doctor' creates this:
'FVM Doctor:                                                                                                                      
---------------------------------------------------------------------------------------------------------------------------------
Project:
┌─────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────┐
│ Project                     │ flutter_thingsboard_app-master                                                    │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Directory                   │ /Users/philipraistrick/flutter_thingsboard_app-master                             │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Active Flavor               │ None                                                                              │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Is Flutter Project          │ Yes                                                                               │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Dart Tool Generator Version │ 3.4.4                                                                             │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Dart tool version           │ 3.22.3                                                                            │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ .gitignore Present          │ Yes                                                                               │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Config Present              │ Yes                                                                               │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Pinned Version              │ FlutterVersion(name: 3.19.6, releaseFromChannel: null, type: VersionType.release) │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Config path                 │ .fvmrc                                                                            │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Local cache dir             │ .fvm/versions                                                                     │
├─────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ Version symlink             │ .fvm/versions/3.19.6                                                              │
└─────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────┘


IDEs:
┌────────────────────────────────┬────────────────────────────────┐
│ IDEs                           │ Value                          │
├────────────────────────────────┼────────────────────────────────┤
│ VSCode                         │                                │
├────────────────────────────────┼────────────────────────────────┤
│ VSCode                         │ No .vscode directory found     │
├────────────────────────────────┼────────────────────────────────┤
│ IntelliJ (Android Studio, ...) │                                │
├────────────────────────────────┼────────────────────────────────┤
│ flutter.sdk                    │ /Users/philipraistrick/flutter │
├────────────────────────────────┼────────────────────────────────┤
│ Matches pinned version:        │ false                          │
├────────────────────────────────┼────────────────────────────────┤
│ IntelliJ (Android Studio, ...) │ No .idea folder found          │
└────────────────────────────────┴────────────────────────────────┘

Environment:
┌────────────────────────┬────────────────────────────────────────────┐
│ Environment Variables  │ Value                                      │
├────────────────────────┼────────────────────────────────────────────┤
│ Flutter PATH           │ /Users/philipraistrick/flutter/bin/flutter │
├────────────────────────┼────────────────────────────────────────────┤
│ Dart PATH              │ /Users/philipraistrick/flutter/bin/dart    │
├────────────────────────┼────────────────────────────────────────────┤
│ FVM_CACHE_PATH         │ N/A                                        │
├────────────────────────┼────────────────────────────────────────────┤
│ FVM_USE_GIT_CACHE      │ N/A                                        │
├────────────────────────┼────────────────────────────────────────────┤
│ FVM_GIT_CACHE_PATH     │ N/A                                        │
├────────────────────────┼────────────────────────────────────────────┤
│ FVM_FLUTTER_URL        │ N/A                                        │
├────────────────────────┼────────────────────────────────────────────┤
│ FVM_PRIVILEDGED_ACCESS │ N/A                                        │
├────────────────────────┼────────────────────────────────────────────┤
│ Flutter PATH           │ /Users/philipraistrick/flutter/bin/flutter │
├────────────────────────┼────────────────────────────────────────────┤
│ Dart PATH              │ /Users/philipraistrick/flutter/bin/dart    │
└────────────────────────┴────────────────────────────────────────────┘
┌──────────────┬──────────────────────────────────────────────────────────────────┐
│ Platform     │ Value                                                            │
├──────────────┼──────────────────────────────────────────────────────────────────┤
│ OS           │ macos Version 14.5 (Build 23F79)                                 │
├──────────────┼──────────────────────────────────────────────────────────────────┤
│ Dart Locale  │ da-DK                                                            │
├──────────────┼──────────────────────────────────────────────────────────────────┤
│ Dart runtime │ 3.2.6 (stable) (Wed Jan 24 13:41:58 2024 +0000) on "macos_arm64" │
└──────────────┴──────────────────────────────────────────────────────────────────┘'

**Comment by ybeshkarov** [comment]
With `fvm` then 
- `fvm use 3.16.6`
- `fvm flutter run` or via IDE but don't forget to select the proper sdk

**Comment by PhilipRai** [comment]
`philipraistrick@MBPtilhdePhilip flutter_thingsboard_app-master % fvm use 3.19.6
✗ Could not resolve dependencies. (31.5s)

Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of flutter_localizations from sdk depends on intl 0.19.0 and thingsboard_app depends on intl ^0.18.1, flutter_localizations from sdk is forbidden.
So, because thingsboard_app depends on flutter_localizations from sdk, version solving failed.

The error could indicate incompatible dependencies to the SDK.
✔ Would you like to continue pinning this version anyway? · yes                                                                  
✓ Project now uses Flutter SDK : SDK Version : 3.19.6

philipraistrick@MBPtilhdePhilip flutter_thingsboard_app-master % fvm flutter run
Resolving dependencies... 
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of flutter_localizations from sdk depends on intl 0.19.0 and thingsboard_app depends on intl ^0.18.1,
  flutter_localizations from sdk is forbidden.
So, because thingsboard_app depends on flutter_localizations from sdk, version solving failed.`

**Comment by ybeshkarov** [comment]
Run` fvm flutter --version`. Must be the same output I provided above.
If not then you need to fix your local environment to reach the same result.

**Comment by PhilipRai** [comment]
Exactly the same:
`Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (4 months ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1`

**Comment by ybeshkarov** [comment]
This is an issue with your local environment. Fix them and the project will build successfully.

**Comment by PhilipRai** [comment]
Solved it. Ditched the `fvm` and downgraded flutter to the correct version instead.

**Comment by ellenfel** [comment]
I was also stuck at same problem (`Error (Xcode): lib/modules/dashboard/dashboard.dart:161:35: Error: The argument type 'Uri' can't be assigned to the parameter type 'WebUri?'.`)

at branch `release/1.2.0`

downgraded the flutter to ` 3.19.6 ` 

now getting the output of :

```
Resolving dependencies... (2.3s)
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of flutter_localizations from sdk depends on intl 0.19.0
  and thingsboard_app depends on intl ^0.18.1, flutter_localizations from sdk is
  forbidden.
So, because thingsboard_app depends on flutter_localizations from sdk, version
  solving failed.
```


at `flutter run`.

tried `flutter update-packages --force-upgrade` didn't helped.

flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on Ubuntu 22.04.4 LTS 6.5.0-45-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

`pubspec.yaml` is unchanged

`flutter --version` output:
```
Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (4 months ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1
```


i am trying on `static const thingsBoardApiEndpoint = 'https://demo.thingsboard.io';`

i've been trying to fix this for few hours now i would really appreciate any help.

**Comment by ybeshkarov** [comment]
Did you use `fvm`? if yes it may replace your global flutter.

@ellenfel

**Comment by ellenfel** [comment]
@ybeshkarov 

no i have not. 
just followed this instructions to install flutter. `https://docs.flutter.dev/get-started/install/linux/android`,  for version 3.19.6

**Comment by ybeshkarov** [comment]
Try to call `flutter clean` in the project root directory.

**Comment by ellenfel** [comment]
i have. Also tried `flutter pub get`

**Comment by ybeshkarov** [comment]
Don't change any dependency version in the `pubspec.yaml`.
Try to clean your pub cache `dart pub cache clean` and then call `flutter run`.

**Comment by ellenfel** [comment]
got it `pubspec.yaml` is unchanged.

just in case i deleted entire repo and re-cloned it.
only change is : `  static const thingsBoardApiEndpoint = 'https://demo.thingsboard.io';`

restarted android-studio.



unfortunately issue still stands after `dart pub cache clean` .
its the same error with `pub get`.
` Because thingsboard_app depends on intl ^0.19.1 which doesn't match any versions, version solving failed.`dart pub cache clean

![Screenshot from 2024-08-07 16-38-32](https://github.com/user-attachments/assets/c5df695f-527f-4b4d-a42b-31192a1deb6c)

**Comment by ybeshkarov** [comment]
@ellenfel are you sure you are using the `master` or `release/1.2.0 `branch? Only the dev branch uses `intl: ^0.19.0`. I wondering if there is any issue that could be with your branches.

**Comment by ellenfel** [comment]
yes i cloned it as such : `git clone -b release/1.2.0 https://github.com/thingsboard/flutter_thingsboard_app.git`
also git branch shows only `release/1.2.0` also in `pubspec.yaml` dependinciy is as, `  intl: ^0.18.1`

i can try compiling `dev` branch if it can compile 3.7 ?

@ybeshkarov

**Comment by ellenfel** [comment]
compiling dev branch gives the following output:

```
Resolving dependencies... (1.9s)
The current Dart SDK version is 3.3.4.

Because thingsboard_app depends on form_builder_validators >=10.0.0 which requires SDK version
  >=3.4.0 <4.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try using the Flutter SDK version: 3.24.0. 

```

i did tried with compiling the branch `dev` with 3.24 before like it suggest  in error message. But then it would gived errors like such :`Error (Xcode): lib/modules/dashboard/dashboard.dart:161:35: Error: The argument type 'Uri' can't be assigned to the parameter type 'WebUri?'`

**Comment by ybeshkarov** [comment]
I just checked on Ubuntu with freshly installed Flutter 3.19.6 and it works normally. 
Check your local environment, and make sure you using 3.19.6 and nothing else.

**Comment by ellenfel** [comment]
@ybeshkarov  thanks a lot for testing. i will try again with fresh install as well.

```
$ flutter --version
Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (4 months ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1
```

my current flutter is like this tho maybe iam missing something else?
will look into it

**Comment by ellenfel** [comment]
adding following to `pubspec.yaml` did the trick:

```
dependency_overrides:
  intl: any
  leak_tracker_flutter_testing: 3.0.3
  leak_tracker_testing: 3.0.1
```
