### ISSUE TITLE
solution for flutter build of thingsboard mobile app and notification(FCM) problem

### ISSUE THREAD

**Issue by philiaa** [thingsboard/flutter_thingsboard_app#106]
hi everyone...
i always thnaks for thingsboard team....^^....
thngsboard is great platform and good for iot....

when build thingsboard mobile app on flutter....got some issues... because each local envionment
i also tried solve for some issues...i got several solutions....
so I would like to share several solutions with everyone

my server spec : ubuntu20.06 lts 
thingsboard version : 3.70(no problems for installl and use, just followed install step in [install document)](https://thingsboard.io/docs/user-guide/install/ubuntu/)
thingsboard install option : postgresql, queue(in memory) 

network settings : server(thingsboard)->router(Port forwarding and DDNS service)->http://xxxx.xxxx.com:8080(just for test)

flutter development environment : android sdk API 35(installed on android studio). flutter sdk 3.19.6(**very important**) 
![image](https://github.com/user-attachments/assets/4c90b596-7186-4e45-8b9f-c39e7d40c748)

thingsboard mobile app verion : 1.1.0 and 1.2.0 ..tested

1. don't change pubspec.yaml ( most of user changed pubspec.yaml, because warning message)
![Screenshot from 2024-08-09 12-21-13](https://github.com/user-attachments/assets/dc00a8dd-acb4-4cd2-be08-1717b0f1fb2b)

FIRST RED WARNING :  grdle plug in warning --> modify some gradle file, but you can ignore that's waring_
if you want remove thats waring --->https://stackoverflow.com/questions/78032396/applying-flutters-app-plugin-loader-gradle-plugin-imperatively-using-the-apply-s

2. SECOND RED WARNING : -Xlint:deporecation issues --> need three step command
flutter pub cache repair
flutter pub cache clean
flutter pub get
and then flutter run or flutter build apk --release --target-platform=android-arm64 (for test on your device)

3. push notification via FCM( did not solved)
******if you need firebase, you do it this step firstly***********

i followd all step in https://thingsboard.io/docs/mobile/getting-started/

Step 3. Configure ThingsBoard API endpoint( most of user mistyped addresss , my sever addresss : http://xxxx.xxxx.com:8080(DDNS address)

Step 4.1 Create Firebase project( you can setting on firebase site....very ease)
Step 4.2 Add Firebase to your mobile application
--> firebase Cli install--> https://firebase.google.com/docs/cli#setup_update_cli

--> firebase log in --> your prompt(linux or windows) $ firebase login

--> flutterfire_cli activate --> your prompt(linux or windows) $ dart pub global activate flutterfire_cli

and then
firebase configuration for your app

flutter_thingsboard_app(your thingsboard mobile app project folder) $ flutterfire configure

you can choice two step( first is your firbase project name and then firbase for android or ios)

![KakaoTalk_20240809_132445744_03](https://github.com/user-attachments/assets/4c9e9689-2bab-4d29-87bf-9590d3c3af1e)
![KakaoTalk_20240809_132445744_02](https://github.com/user-attachments/assets/6d99853b-f1c0-4bc7-bf66-7cbe377ebfb4)
![KakaoTalk_20240809_132445744_01](https://github.com/user-attachments/assets/e1ef3d0c-390d-4eea-9376-84f11bd6f30f)

ALL IS OK BUT.......push notification problem
send message to app from firebase console (work well)
![KakaoTalk_20240809_132445744](https://github.com/user-attachments/assets/056e3869-d31c-46e3-8bab-6c3e1de473f4)

but when i send mobile message on thingsboard notification center  ..... "User doesn't use the mobile app" error.
so i tried check all source and db....but i cant solve that
![KakaoTalk_20240809_132445744_05](https://github.com/user-attachments/assets/258e2b14-409a-4786-9e79-b38c499e5470)
touch Notifications
![KakaoTalk_20240809_132445744_04](https://github.com/user-attachments/assets/93c57b71-42b4-4347-b3fa-f413dc8c2562)
Notifications are not configured. Please contact your system administrator error

thingsboard cloud app is not happend that's error.(customer login and then touch notification, show notification informaton well)...
so i think thats issues on thingsboard ce version.... 
thanks for all
and thanks for thingsboard team

**Comment by C3sarz** [comment]
Thank you for your contribution, I was also having difficulties compiling the app with the newest flutter SDK. By downgrading flutter to 3.19.6 the app finally did compile.

**Comment by ybeshkarov** [comment]
Hello @philiaa,

Thank you for your contribution and for helping to improve the ThingsBoard app.

Could you let me know if you configured Firebase for the mobile app locally? Also, have you noticed any changes in the lib/firebase_options.dart file?

**Comment by philiaa** [comment]
hello @ybeshkarov 

i just configured private key of Firebase on local server(settings->notification->mobile settings)....
don't have any changed in the lib/firebase_options.dart file....Same as the original file([flutter_thingsboard_app](https://github.com/thingsboard/flutter_thingsboard_app/tree/master)  github source)

**Comment by ybeshkarov** [comment]
You'll also need to complete steps 4.2 - 4.3 from the [Getting Started guide](https://thingsboard.io/docs/pe/mobile/getting-started/).

@philiaa

**Comment by philiaa** [comment]
@ybeshkarov 
yes of course....i did complete steps 4.2 - 4.3 from the [Getting Started guide](https://thingsboard.io/docs/pe/mobile/getting-started/). for android without ios
1. $ firebase login
2. $ dart pub global activate flutterfire_cli
3. project folder$ flutterfire configure
and then
created firebase_options.dart file (but same as original file from flutter_thingsboard_app source)
check contain -> android/app/google-services.json

if i didn't this step.....i think that i can't push alram message from firebase console directly.....

help me~~please......if i can solve that;s problem...thingsboard is my perfect iot platform for smartfarm in korea

**Comment by ybeshkarov** [comment]
That's odd. After running flutterfire configure, the firebase_options.dart file should have been updated.

Did you select 'yes' when flutterfire configure prompted you to replace the file?

**Comment by philiaa** [comment]
@ybeshkarov 
thank you for reply...and advice
After running flutterfire configure, firebase_options.dart file NOT CHANGED(same as original  firebase_options.dart)
i will show you....my steps for build flutter app
![Screenshot from 2024-08-23 07-09-40](https://github.com/user-attachments/assets/fe6cfb56-8321-4335-968d-54f1c7de1f4d)
![Screenshot from 2024-08-23 07-14-26](https://github.com/user-attachments/assets/3e3b78c7-1f2d-4c20-a516-b84f131a4d6c)
check firebase settings : 
![Screenshot from 2024-08-23 07-18-03](https://github.com/user-attachments/assets/fa66f7d1-705c-4b74-af19-a9be6c6f90ea)
check thingsboard server settings:
![Screenshot from 2024-08-23 07-20-05](https://github.com/user-attachments/assets/37338d7b-36f8-471a-b2c9-04338de3b458)
firebase login and activate :
![Screenshot from 2024-08-23 07-22-12](https://github.com/user-attachments/assets/b9f2914a-024a-4137-a370-dd2a21770060)
flutter firebase configure :
![Screenshot from 2024-08-23 07-24-57](https://github.com/user-attachments/assets/f1ba6852-5528-4657-9525-70fa0c8cc196)
but dont have any changed(same as original file)
![Screenshot from 2024-08-23 07-25-54](https://github.com/user-attachments/assets/88c90b39-3bc9-485f-b7df-19ae4da6f86a)
check google-services.json file
![Screenshot from 2024-08-23 07-28-03](https://github.com/user-attachments/assets/e1a18351-1cfd-4797-92c0-2d53bf30e61b)
solving depandecies :
![Screenshot from 2024-08-23 07-36-30](https://github.com/user-attachments/assets/37b8ee91-2576-47b6-9739-9b59007835a8)
and flutter project build
![Screenshot from 2024-08-23 07-39-56](https://github.com/user-attachments/assets/83057e91-2ed0-435b-84f6-6b1a88ed6003)

**Comment by philiaa** [comment]
@ybeshkarov 
i solved that.....thank you for your advice and reply...
i deleted firebase_options.dart file and then running flutterfire configure again....
i received push notification on android app from notification center on thingsboard server
thank you thingsboard team...^^
