### ISSUE TITLE
Problem with running the program on web

### ISSUE THREAD

**Issue by nima1313** [thingsboard/flutter_thingsboard_app#110]
when I run the program on web I get these error in the log

Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3   assertFailed
packages/dio/src/options.dart 144:52                                         new
packages/thingsboard_client/src/interceptor/http_interceptor.dart 32:28      new
packages/thingsboard_client/src/thingsboard_client_base.dart 94:7            new
packages/thingsboard_app/core/context/tb_context.dart 113:16                 init
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 464:9                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>

also I get stuck in the loading page

![image](https://github.com/user-attachments/assets/9810a15d-b1b8-4878-a44f-08640416e010)

**Comment by nima1313** [comment]
additional informations : I run it on demo.thingsboard.io  .  my flutter SDK version is 3.19.6 .

**Comment by ybeshkarov** [comment]
Hello @nima1313,

Web is not supported. Use can use Android or IOS platforms.
