### ISSUE TITLE
Gradle version

### ISSUE THREAD

**Issue by nima1313** [thingsboard/flutter_thingsboard_app#117]
Hello there. 
I'm using this project from Iran and there are a lot of sanctions on Iran.
the original Gradle version in flutter_thingsboard_app\android\gradle\wrapper\gradle-wrapper.properties doesn't work for Iran no matter how many DNS changers and VPNs you use. (or at least beyond the capabilities of the average contributor). 
but after a lot of experiments I found out gradle-7.6.4 works. I was wondering if it's possible to change the Gradle version of the project to this so that any country with sanctions like Iran doesn't get stuck on this for days.

**Comment by ashvayka** [comment]
Hi @nima1313 , 

Thank you for your feedback and for sharing your experience. 

Given the current geopolitical climate, especially considering the impact of certain actions on our team members who are based in Ukraine, we are not in a position to accommodate requests that specifically address the needs of contributors from countries involved in activities that harm our team.

We encourage you to maintain your fork with the Gradle version that works for you, and we'll continue to focus on supporting the broader community in ways that align with our values.
