### ISSUE TITLE
Widgets Not Displaying in ThingsBoard mobile app

### ISSUE THREAD

**Issue by dani21almc** [thingsboard/flutter_thingsboard_app#134]
Hello,

I am experiencing an issue with ThingsBoard mobile version 1.3. After downloading the compressed file and compiling the application, I am unable to see the widgets within the dashboard.

Here are the steps I followed:

Downloaded the ThingsBoard 1.3 compressed file from here:
https://github.com/thingsboard/flutter_thingsboard_app/releases/tag/v1.3.0

Compiled the application successfully.
Accessed the dashboard, but the widgets do not appear.
I would appreciate any guidance on how to resolve this issue so that I can visualize the widgets properly. Are there any specific settings or configurations I should check?

Thank you for your assistance!

**Comment by ybeshkarov** [comment]
Hello @dani21almc,

Is the dashboard loaded (the loading indicator is gone), and the widgets are not displayed? Or is the dashboard not loading at all (the ThingsBoard logo continuously rotating)?

**Comment by dani21almc** [comment]
Hi, thank you for your answer, the dashboard is not loading at all, like you say the ThingsBoard logo continuously rotating.

**Comment by ybeshkarov** [comment]
Did you try with the demo.thingsboard.io or your custom TB instance?

**Comment by dani21almc** [comment]
I use my own instance, yo use thingsboard in a vos I use this guide https://thingsboard.io/docs/user-guide/install/ubuntu/?ubuntuThingsboardQueue=kafka

In the server, only are open the ports of the ui and mqtt, 8080 and 1883.

**Comment by ybeshkarov** [comment]
You need to wait until the ThingsBoard platform is released and redeploy it. A fix has been added at the platform level.

**Comment by dani21almc** [comment]
Currently im Using the 3.7 version of thingsboard, then I need to wait to the platform of thingsboard releases the versión 3.8 and update, then i can use correctly with the mobile app?

**Comment by ybeshkarov** [comment]
Correct.

**Comment by ybeshkarov** [comment]
Hi @dani21almc,

The ThingsBoard v3.8.0 was release. Could you please update and see if you still have an issue?
