### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by tobiyas09** [thingsboard/flutter_thingsboard_app#135]
I am trying to build the app, but it fails. I am on release/1.3.0 and I am using fvm.

This is the error:

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':device_info_plus:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':device_info_plus:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /Users/tomislavgrdenic/Library/Android/sdk/platforms/android-34/core-for-system-modules.jar.
         > Error while executing process /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/jlink with arguments {--module-path /Users/tomislavgrdenic/.gradle/caches/transforms-3/c66d6905e9178766417c242e6b14a315/transformed/output/temp/jmod --add-modules java.base --output /Users/tomislavgrdenic/.gradle/caches/transforms-3/c66d6905e9178766417c242e6b14a315/transformed/output/jdkImage --disable-plugin system-modules}
         

This is the output of `flutter doctor -v`:

[✓] Flutter (Channel stable, 3.22.2, on macOS 13.5.1 22G90 darwin-arm64, locale
    en-HR)
    • Flutter version 3.22.2 on channel stable at
      /Users/tomislavgrdenic/fvm/versions/3.22.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tomislavgrdenic/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/tomislavgrdenic/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.13.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.94.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.99.20240930

[✓] Connected device (3 available)
    • AC2003 (mobile)                 • 17e83838              • android-arm64 • Android 12 (API 31)
    • macOS (desktop)                 • macos                 • darwin-arm64  • macOS 13.5.1 22G90 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin        • macOS 13.5.1 22G90 darwin-arm64
    ! Error: Browsing on the local area network for Team’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

**Comment by ybeshkarov** [comment]
Hello, 

Never seen this error before. I've googled it a bit and seems it might be connected with a java version. 
I see you have 
`Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)` 
but my is 
`Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)`

Could you try to decrease your java version to see if will it help?

**Comment by tobiyas09** [comment]
Hi, and thanks.

I downgraded java to 17.0.9 and I finally built the app.
