### ISSUE TITLE
Problems with setting the filters for the time curve

### ISSUE THREAD

**Issue by radontec** [thingsboard/flutter_thingsboard_app#14]
I´ve a bug in the iPhone App (Demo App with Demo Thingsboard).
Newest iOS 15.3
![1](https://user-images.githubusercontent.com/58628249/151509059-e73d8a82-a54c-428b-81c2-544f447af360.PNG)

![2](https://user-images.githubusercontent.com/58628249/151509069-529cf254-4bf1-40cb-9994-fc334568ce47.PNG)

![3](https://user-images.githubusercontent.com/58628249/151509075-6de86d49-d3e8-421f-aa54-5628d026057b.PNG)

The Refresh button "Aktualisieren" remains greyed out, the only thing I can do is cancel.

**Comment by vvlladd28** [comment]
Thank you for reporting the issue,
This issue will be resolved in TB 3.3.4 version (main product, not mobile app).

**Comment by radontec** [comment]
I´ve tryed with 3.3.4 now it works. thx for fixing it!
