### ISSUE TITLE
App version 1.3.0 says ThingsBoard 3.7.0.15PAAS not supported

### ISSUE THREAD

**Issue by whiskyplausible** [thingsboard/flutter_thingsboard_app#140]
I've successfully built the app versions 1.1.0, 1.2.0 and 1.3.0, but when I run any of them on an Android device I receive the Fatal Error:

"Fatal application error occurred:
Unsupported ThingsBoard platform vesion: 3.7.0.15PAAS"

Is any version of the app compatible with the cloud hosted ThingsBoard at thingsboard.cloud?

**Comment by whiskyplausible** [comment]
Thanks so much for the quick response @ybeshkarov 
I had a go at the PE mobile version as linked, and tried both the 1.3.0 and the 1.1.0 releases, both of them appeared with the same message, "Unsupported ThingsBoard platform vesion: 3.7.0.15PAAS". 

It looks like 1.3.0 supports TB 3.8, so I assume that's why doesn't work, release 1.1.0 says it supports 3.6.3PE+, however still has the same message. Do you know if there's any release version of the flutter pp that does support the version of ThingsBoard running on thingsboard.cloud?

**Comment by ybeshkarov** [comment]
Which version `thingsboard_pe_client` did you use?

**Comment by whiskyplausible** [comment]
I used the default ones in the pubspec.yaml for the respective versions - so client v1.3.1 when I tried the 1.3.0 app, and client v1.1.0 when I tried the 1.1.0 app.

**Comment by ybeshkarov** [comment]
Got it. The cloud is scheduled to be updated tomorrow. Please wait until it’s upgraded to version 3.8.0 and try again.

**Comment by whiskyplausible** [comment]
OK, that's great - will try later in the week. Thank you for looking into it.
