### ISSUE TITLE
Not implemented! message when I open a dashboard. 

### ISSUE THREAD

**Issue by ahmed-1a** [thingsboard/flutter_thingsboard_app#15]
Hi,

I'm testing thingsboard mobile app with demo.thingsboard.io, I get "Not implemented!" message when I open any dashboard.
So, I cannot see any widgets.

Have you faced a similar problem, how can I solve this issue?

Thanks.

![image](https://user-images.githubusercontent.com/41074884/151769498-169b28fa-6456-4200-be29-f675499795ad.png)

**Comment by ahmed-1a** [comment]
The problem happened using android 12 SDK API version 31. 
On Android 11, it works without any problem.

**Comment by alpha512** [comment]
I also met this problem. How do u solve problems?

**Comment by yunamoon** [comment]
Did you solve the problem?

**Comment by ybeshkarov** [comment]
Hello @ahmed-1a!

Are you still facing this issue?
