### ISSUE TITLE
assembleDebug error

### ISSUE THREAD

**Issue by ricc187** [thingsboard/flutter_thingsboard_app#155]
_I'm a Student who's making a IoT project with ThingsBoard and I'm trying to run the app from the source code. So I cloned it and i only wanted to first start it with "flutter run". And i have this error. Please help me_ 

**Error: **
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply

../AppData/Local/Pub/Cache/hosted/pub.dev/win32-5.1.0/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/win32-5.1.0/lib/src/guid.dart:32:9: Error: 'UnmodifiableUint8ListView' isn't a type.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/win32-5.1.0/lib/src/guid.dart:52:17: Error: Method not found: 'UnmodifiableUint8ListView'.
    return Guid(UnmodifiableUint8ListView(guid));
                ^^^^^^^^^^^^^^^^^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/win32-5.1.0/lib/src/guid.dart:56:31: Error: Method not found: 'UnmodifiableUint8ListView'.
  factory Guid.zero() => Guid(UnmodifiableUint8ListView(Uint8List(16)));
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/win32-5.1.0/lib/src/guid.dart:100:17: Error: Method not found: 'UnmodifiableUint8ListView'.
    return Guid(UnmodifiableUint8ListView(Uint8List.fromList(guidAsBytes)));
                ^^^^^^^^^^^^^^^^^^^^^^^^^
lib/core/context/tb_context.dart:127:26: Error: Can't declare a member that conflicts with an inherited one.
  PopInvokedCallback get onPopInvoked => onPopInvokedImpl;
                         ^^^^^^^^^^^^
../dev/flutter/packages/flutter/lib/src/widgets/routes.dart:2476:8: Context: This is the inherited member.
  void onPopInvoked(bool didPop) { }
       ^^^^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_html-3.0.0-alpha.5/lib/style.dart:239:47: Error: The getter 'headline1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../dev/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline1'.
    'h1': Style.fromTextStyle(theme.textTheme.headline1!),
                                              ^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_html-3.0.0-alpha.5/lib/style.dart:240:47: Error: The getter 'headline2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../dev/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline2'.
    'h2': Style.fromTextStyle(theme.textTheme.headline2!),
                                              ^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_html-3.0.0-alpha.5/lib/style.dart:241:47: Error: The getter 'headline3' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../dev/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline3'.
    'h3': Style.fromTextStyle(theme.textTheme.headline3!),
                                              ^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_html-3.0.0-alpha.5/lib/style.dart:242:47: Error: The getter 'headline4' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../dev/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline4'.
    'h4': Style.fromTextStyle(theme.textTheme.headline4!),
                                              ^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_html-3.0.0-alpha.5/lib/style.dart:243:47: Error: The getter 'headline5' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../dev/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline5'.
    'h5': Style.fromTextStyle(theme.textTheme.headline5!),
                                              ^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_html-3.0.0-alpha.5/lib/style.dart:244:47: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../dev/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
    'h6': Style.fromTextStyle(theme.textTheme.headline6!),
                                              ^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_html-3.0.0-alpha.5/lib/style.dart:245:49: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../dev/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
    'body': Style.fromTextStyle(theme.textTheme.bodyText2!),
                                                ^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_html-3.0.0-alpha.5/lib/html_parser.dart:153:62: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../dev/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
      style: Style.fromTextStyle(Theme.of(context).textTheme.bodyText2!),
                                                             ^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_html-3.0.0-alpha.5/lib/html_parser.dart:217:72: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../dev/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
                style: Style.fromTextStyle(Theme.of(context).textTheme.bodyText2!),
                                                                       ^^^^^^^^^
lib/core/auth/login/two_factor_authentication_page.dart:357:35: Error: The argument type 'String' can't be assigned to the parameter type 'RegExp'.
 - 'RegExp' is from 'dart:core'.
      FormBuilderValidators.match(pattern,
                                  ^
Target kernel_snapshot_program failed: Exception

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script 'C:\Users\administrator\dev\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1687

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\administrator\dev\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Running Gradle task 'assembleDebug'...                              9,0s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by ybeshkarov** [comment]
Hi,

Please check if this response will help you resolve the issue https://github.com/thingsboard/flutter_thingsboard_pe_app/issues/194#issuecomment-2489107289
