### ISSUE TITLE
When I login flutter app, automatically gets logout

### ISSUE THREAD

**Issue by parkeunsoo** [thingsboard/flutter_thingsboard_app#16]
When I login flutter app, Exception occurs below Screenshot
----
Please fix it...

ThingsBoard Version: 3.2.2
android 11 API 30

I paste screenshot debugging
<img width="1434" alt="스크린샷 2022-02-02 오후 11 31 25" src="https://user-images.githubusercontent.com/32799518/152176377-3252d7b2-fe73-46c2-bdd9-c8090137d3cd.png">

**Comment by ybeshkarov** [comment]
Hello, @parkeunsoo!

Are you still facing this issue?
