### ISSUE TITLE
Fatal application error occurred: Unsupported Thingsboard version :3.8.1.7PASS

### ISSUE THREAD

**Issue by ThinLizzy13** [thingsboard/flutter_thingsboard_app#165]
Similar issue to [this](https://github.com/thingsboard/flutter_thingsboard_app/issues/51)

Using Flutter ThingsBoard Mobile Application version: 1.4.0

Judging from[ here looks like TB version hadn't been updated from 3.8.1PE to 3.8.1PE+](https://thingsboard.io/docs/pe/mobile/getting-started/#step-2-get-app-source-code)
![Image 29-11-2024 at 21 11](https://github.com/user-attachments/assets/b4d6beb7-4123-44b1-ba1b-cc387b94232e)

**Comment by ybeshkarov** [comment]
You cannot use the CE mobile app with the PE TB version. 

Btw the issue you're referring to has the same answer.
