### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by diegus22** [thingsboard/flutter_thingsboard_app#17]
Hello,

The first time I run the application in the simulator, it gets stuck in the initial screen, in order to continue I have to stop the simulation and restart the application, in this case, I access the login screen and I can enter the credentials, but it gets stuck again, it is in the third run when I can actually enter the dashboard.

![error](https://user-images.githubusercontent.com/333989/152518118-7bf07d7a-cbf3-40da-96bd-e5e6e36793fd.PNG)

**Comment by Ataraxiall** [comment]
Same error here...Any solution?

**Comment by ybeshkarov** [comment]
Hello, @diegus22!

Could you please clarify if you see this issue with the latest code base?

**Comment by ybeshkarov** [comment]
Closed as no response.
