### ISSUE TITLE
change the login background color

### ISSUE THREAD

**Issue by jbanlles-vunkers** [thingsboard/flutter_thingsboard_app#175]
I've been struggling for a few hours to find where to change the login background color if you could help me. Thank you!

**Comment by ybeshkarov** [comment]
You may change the color of corner elements 
![Screenshot 2024-12-17 at 12 06 39](https://github.com/user-attachments/assets/ad77f69a-a5a2-457d-8e52-bed6c31405b9)
<img width="1840" alt="Screenshot 2024-12-17 at 12 06 25" src="https://github.com/user-attachments/assets/abf41abc-6393-480d-9a36-26583b777e0c" />

This is for the background 
<img width="1840" alt="Screenshot 2024-12-17 at 12 22 03" src="https://github.com/user-attachments/assets/0d885657-9a2f-42b7-9bcc-1a317962611a" />

**Comment by jbanlles-vunkers** [comment]
Thank you so much! I have already solved it
