### ISSUE TITLE
Error on flutter run...

### ISSUE THREAD

**Issue by AngeLinuX99** [thingsboard/flutter_thingsboard_app#18]
Hi, 

I got this error when i launch a flutter run command, any help to solve it ??
Thanks !
-----
Running "flutter pub get" in flutter_thingsboard_app...             3,9s
Launching lib\main.dart on M2101K9AG in debug mode...
lib/modules/dashboard/dashboard.dart:384:87: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
                                  var data = MediaQueryData.fromWindow(WidgetsBinding.instance!.window);
                                                                                      ^
lib/core/auth/login/login_page.dart:188:71: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
                  var data = MediaQueryData.fromWindow(WidgetsBinding.instance!.window);
                                                                      ^
lib/core/auth/web/tb_web_auth.dart:27:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(_resumedObserver); // safety measure so we never add this observer twice
                   ^
lib/core/auth/web/tb_web_auth.dart:28:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(_resumedObserver);
                   ^
lib/core/auth/web/tb_web_auth.dart:38:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(_resumedObserver);
                   ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/qr_code_scanner-0.6.1/lib/src/qr_code_scanner.dart:68:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(_observer);
                   ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/qr_code_scanner-0.6.1/lib/src/qr_code_scanner.dart:86:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(_observer);
                   ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/infinite_scroll_pagination-3.1.0/lib/src/ui/paged_sliver_builder.dart:257:24: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance?.addPostFrameCallback((_) {
                       ^
Note: C:\Users\anglm\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\device_info-2.0.3\android\src\main\java\io\flutter\plugins\deviceinfo\DeviceInfoPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
e: C:\Users\anglm\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.6.1\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (23, 1): Class 'QRView' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: C:\Users\anglm\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.6.1\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (217, 26): Null can not be a value of a non-null type String
e: C:\Users\anglm\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.6.1\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (248, 26): Null can not be a value of a non-null type String
e: C:\Users\anglm\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.6.1\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRView.kt: (301, 5): 'onRequestPermissionsResult' overrides nothing
e: C:\Users\anglm\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.6.1\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRViewFactory.kt: (10, 1): Class 'QRViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\Users\anglm\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.6.1\android\src\main\kotlin\net\touchcapture\qr\flutterqr\QRViewFactory.kt: (13, 5): 'create' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qr_code_scanner:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 13s
Running Gradle task 'assembleDebug'...                             75,0s
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by ybeshkarov** [comment]
Hello @AngeLinuX99!

I'm not able to reproduce this issue. Is it reproducible for you?
Thank you!

**Comment by ybeshkarov** [comment]
Closed as no response.
