### ISSUE TITLE
How can I connect our own server

### ISSUE THREAD

**Issue by DiamoandDog** [thingsboard/flutter_thingsboard_app#2]
When I launch the app and enter the landing page, how do I set my server address
[
![Simulator Screen Shot - iPhone 11 - 2021-07-22 at 14 43 55](https://user-images.githubusercontent.com/14171367/126599276-25aa4106-0b17-441c-9e64-cb33f1bc2e44.png)
](url)

**Comment by vvlladd28** [comment]
Hi @DiamoandDog,
Your need to edit variable thingsBoardApiEndpoint in file lib/constants/app_constants.dart

**Comment by DiamoandDog** [comment]
> Hi @DiamoandDog,
> Your need to edit variable thingsBoardApiEndpoint in file lib/constants/app_constants.dart

Thank you so much ！And now we encounter a new problem. In the tb_context.dart file, an error is thrown when running to ‘homeDashboard = await tbClient.getDashboardService().getHomeDashboardInfo();’, and then the program executes logout(). We seem to be unable to request the api of'/api/dashboard/home/info'. I want to know what is causing this problem. How can I solve this problem?

**Comment by angrymango** [comment]
@DiamoandDog I hit the same issue. If you look at the dart client it supports the unreleased thingsboard v3.3.0 https://github.com/thingsboard/dart_thingsboard_client. I ran it against a build from the master branch and it works.

**Comment by DiamoandDog** [comment]
> @DiamoandDog I hit the same issue. If you look at the dart client it supports the unreleased thingsboard v3.3.0 https://github.com/thingsboard/dart_thingsboard_client. I ran it against a build from the master branch and it works.

Sorry，I think I have used the v3.3.0 version of the client, but I now find a problem. In the v3.3.0 environment we deployed, we did not find the'/ in ThingsBoard REST API (in swagger-ui.html page) api/dashboard/home/info', but in the environment of'http://demo.thingsboard.io/', you can find this api. What is the cause of this, and how can I solve it?

**Comment by RTL8710** [comment]
> > @DiamoandDog I hit the same issue. If you look at the dart client it supports the unreleased thingsboard v3.3.0 https://github.com/thingsboard/dart_thingsboard_client. I ran it against a build from the master branch and it works.
> 
> Sorry，I think I have used the v3.3.0 version of the client, but I now find a problem. In the v3.3.0 environment we deployed, we did not find the'/ in ThingsBoard REST API (in swagger-ui.html page) api/dashboard/home/info', but in the environment of'http://demo.thingsboard.io/', you can find this api. What is the cause of this, and how can I solve it?



> When I launch the app and enter the landing page, how do I set my server address
> [ ![Simulator Screen Shot - iPhone 11 - 2021-07-22 at 14 43 55](https://user-images.githubusercontent.com/14171367/126599276-25aa4106-0b17-441c-9e64-cb33f1bc2e44.png) ](url)


我也遇到这个问题了， 希望可以联系，共同学习thingsboard，谢谢咯

**Comment by DiamoandDog** [comment]
> > > @DiamoandDog I hit the same issue. If you look at the dart client it supports the unreleased thingsboard v3.3.0 https://github.com/thingsboard/dart_thingsboard_client. I ran it against a build from the master branch and it works.
> > 
> > 
> > Sorry，I think I have used the v3.3.0 version of the client, but I now find a problem. In the v3.3.0 environment we deployed, we did not find the'/ in ThingsBoard REST API (in swagger-ui.html page) api/dashboard/home/info', but in the environment of'http://demo.thingsboard.io/', you can find this api. What is the cause of this, and how can I solve it?
> 
> > When I launch the app and enter the landing page, how do I set my server address
> > [ ![Simulator Screen Shot - iPhone 11 - 2021-07-22 at 14 43 55](https://user-images.githubusercontent.com/14171367/126599276-25aa4106-0b17-441c-9e64-cb33f1bc2e44.png) ](url)
> 
> 我也遇到这个问题了， 希望可以联系，共同学习thingsboard，谢谢咯

你看第二条，他已经回复我了，就是改那个文件里的地址

**Comment by IoTThinks** [comment]
@vvlladd28 Do you have any screenshot after login? Very curious.
Thanks a lot.

**Comment by vvlladd28** [comment]
Hi @IoTThinks,
Screenshots after login on the mobile app: 
![image](https://user-images.githubusercontent.com/18036670/130048022-6e780711-b930-4297-b319-037f34b4fb09.png)
![image](https://user-images.githubusercontent.com/18036670/130048049-03616ee5-b81f-451c-8823-41c9c7a57d10.png)
![image](https://user-images.githubusercontent.com/18036670/130048067-bece44d3-8695-40c7-80ed-fd4d1cc8b874.png)
![image](https://user-images.githubusercontent.com/18036670/130048410-ed510aa8-ef68-45bc-acb9-3b91971c8dd1.png)

**Comment by IoTThinks** [comment]
So great. I'm trying now.

Still newbie in mobile development.
Thanks a lot.
