### ISSUE TITLE
Feature request - notifications to created alarms

### ISSUE THREAD

**Issue by yadunandan6176** [thingsboard/flutter_thingsboard_app#20]
The feature can be to notify the customers when the alarm is created in the thingsboard's dashboard. The notification could appear in the notification panel.   
I would like to know if it can be done individually.

**Comment by ezeroldan24** [comment]
Good afternoon! Could you solve it?

**Comment by ybeshkarov** [comment]
We will work on this feature in future releases. 

Stay tuned :)
