### ISSUE TITLE
Diferent home dashborad App/web

### ISSUE THREAD

**Issue by Ataraxiall** [thingsboard/flutter_thingsboard_app#23]
I have the problem with the dashboards, if a client enters via the web, I want one of the dashboards to be opened directly, I configure this as the default dashboard in the client, but in the app, I do not want this to happen, I want them to appear dashboard icons, but if I apply a default panel to the client, this does not happen. Any idea?

Thanks!

**Comment by ybeshkarov** [comment]
Hello, @Ataraxiall!

Please be informed web is not supported.
