### ISSUE TITLE
Can't run in Flutter 3.0.0

### ISSUE THREAD

**Issue by jiekechoo** [thingsboard/flutter_thingsboard_app#24]
e: /Users/jiekechoo/devel/flutterSDK3/.pub-cache/hosted/pub.flutter-io.cn/qr_code_scanner-0.5.2/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (23, 1): Class 'QRView' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /Users/jiekechoo/devel/flutterSDK3/.pub-cache/hosted/pub.flutter-io.cn/qr_code_scanner-0.5.2/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (214, 26): Null can not be a value of a non-null type String
e: /Users/jiekechoo/devel/flutterSDK3/.pub-cache/hosted/pub.flutter-io.cn/qr_code_scanner-0.5.2/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (245, 26): Null can not be a value of a non-null type String
e: /Users/jiekechoo/devel/flutterSDK3/.pub-cache/hosted/pub.flutter-io.cn/qr_code_scanner-0.5.2/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (273, 5): 'onRequestPermissionsResult' overrides nothing
e: /Users/jiekechoo/devel/flutterSDK3/.pub-cache/hosted/pub.flutter-io.cn/qr_code_scanner-0.5.2/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt: (10, 1): Class 'QRViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /Users/jiekechoo/devel/flutterSDK3/.pub-cache/hosted/pub.flutter-io.cn/qr_code_scanner-0.5.2/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt: (13, 5): 'create' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qr_code_scanner:compileDebugKotlin'.
> Compilation error. See log for more details

reference : [[BUG] Can't run in flutter 3 #532 ](https://github.com/juliuscanute/qr_code_scanner/issues/532)

**Comment by rudian** [comment]
me too facing the same problem

**Comment by IoTThinks** [comment]
Over here says  sdk: ">=2.12.0 <3.0.0"
https://github.com/thingsboard/flutter_thingsboard_app/blob/master/pubspec.yaml#L9

However, 2.12.x doesnt have any stable versions. Only beta version has 2.12.x.
https://docs.flutter.dev/development/tools/sdk/releases

**Comment by IoTThinks** [comment]
@jiekechoo So we need to change qr_code_scanner: ^0.6.1 to qr_code_scanner: ^1.0.0?
Have you made it working? Thanks a lot.

**Comment by jiekechoo** [comment]
> @jiekechoo So we need to change qr_code_scanner: ^0.6.1 to qr_code_scanner: ^1.0.0? Have you made it working? Thanks a lot.

not yet. I still use Flutter 2 for development. I have two develop environment , use linux command ln -s change Flutter 2 or 3 for build specific apps.

**Comment by IoTThinks** [comment]
> @jiekechoo So we need to change qr_code_scanner: ^0.6.1 to qr_code_scanner: ^1.0.0?
> 
> Have you made it working? Thanks a lot.

This approach works.
I can run the app on Flutter 3 now.
Have some warnings during compilation btw.

**Comment by iRobinZhang** [comment]
after struggle with this issue,  solved as follows:
1) force use 
Flutter 3.0.0 
Dart 2.17.0 
DevTools 2.12.2

2) change android  compileSdkVersion from 31 to 32  in app/build.gradle 

Then the app can launch running on device ,

 yes, it still throw some red warning ( looks can ignore temporary  )
