### ISSUE TITLE
[BUG] Cannot login if user has 2FA activated.

### ISSUE THREAD

**Issue by fjpanag** [thingsboard/flutter_thingsboard_app#25]
If a user enables 2FA, login is impossible.

The user enters the correct credentials, but when they tap "Log In" nothing happens.

**Comment by asdshop** [comment]
Same problem. Running TB version 3.4.2 and giving correct credentials user not able to login. Has someone the answer?

**Comment by Ifousoft** [comment]
What is 2FA?
I got the same problem. I login and nothing happens. Neither error message in the flutter terminal.
Using a wrong password, I got a message...
How to solve that?

**Comment by Philip2809** [comment]
Even worse now with latest update #92

**Comment by ybeshkarov** [comment]
Hello guys,

An issue will be fixed in the 1.2.0 release. Stay tuned.
