### ISSUE TITLE
Unsupported ThingsBoard platform version: unknown

### ISSUE THREAD

**Issue by shiyuecamus** [thingsboard/flutter_thingsboard_app#28]
versions:
thingsboard: 3.3.4
flutter_thingsboard_app: latest
ext.kotlin_version: '1.7.10'
gradle: 6.7.1

I received the following error when starting the project:

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
√  Built build\app\outputs\flutter-apk\app-debug.apk.
D/FlutterGeolocator( 6521): Attaching Geolocator to activity
W/FlutterActivityAndFragmentDelegate( 6521): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
D/FlutterGeolocator( 6521): Creating service.
D/FlutterGeolocator( 6521): Binding to location service.
D/FlutterGeolocator( 6521): Geolocator foreground service connected
D/FlutterGeolocator( 6521): Initializing Geolocator services
Debug service listening on ws://127.0.0.1:64067/MsBq8uDfTpw=/ws
Syncing files to device Android SDK built for x86...
I/flutter ( 6521):   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6521):   ERROR │ ThingsboardError: message: [Unsupported ThingsBoard platform version: unknown], errorCode: 2, status: null
I/flutter ( 6521):   ERROR │ #0      toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:89:18)
I/flutter ( 6521):   ERROR │ #1      ThingsboardClient.init (package:thingsboard_client/src/thingsboard_client_base.dart:216:13)
I/flutter ( 6521):   ERROR │ <asynchronous suspension>
I/flutter ( 6521):   ERROR │ #2      TbContext.init (package:thingsboard_app/core/context/tb_context.dart:172:7)
I/flutter ( 6521):   ERROR │ <asynchronous suspension>
I/flutter ( 6521):   ERROR │ #3      HasTbContext.initTbContext (package:thingsboard_app/core/context/tb_context.dart:565:5)
I/flutter ( 6521):   ERROR │ <asynchronous suspension>
I/flutter ( 6521):   ERROR │ 
I/flutter ( 6521):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6521):   ERROR │ #0   ThingsboardClient.init (package:thingsboard_client/src/thingsboard_client_base.dart:216:7)
I/flutter ( 6521):   ERROR │ #1   <asynchronous suspension>
I/flutter ( 6521):   ERROR │ #2   TbContext.init (package:thingsboard_app/core/context/tb_context.dart:172:7)
I/flutter ( 6521):   ERROR │ #3   <asynchronous suspension>
I/flutter ( 6521):   ERROR │ #4   HasTbContext.initTbContext (package:thingsboard_app/core/context/tb_context.dart:565:5)
I/flutter ( 6521):   ERROR │ #5   <asynchronous suspension>
I/flutter ( 6521):   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 6521):   ERROR │ ⛔ Failed to init tbContext: ThingsboardError: message: [Unsupported ThingsBoard platform version: unknown], errorCode: 2, status: null
I/flutter ( 6521):   ERROR │ ⛔ #0      toThingsboardError (package:thingsboard_client/src/error/_thingsboard_error_handler_io.dart:89:18)
I/flutter ( 6521):   ERROR │ ⛔ #1      ThingsboardClient.init (package:thingsboard_client/src/thingsboard_client_base.dart:216:13)
I/flutter ( 6521):   ERROR │ ⛔ <asynchronous suspension>
I/flutter ( 6521):   ERROR │ ⛔ #2      TbContext.init (package:thingsboard_app/core/context/tb_context.dart:172:7)
I/flutter ( 6521):   ERROR │ ⛔ <asynchronous suspension>
I/flutter ( 6521):   ERROR │ ⛔ #3      HasTbContext.initTbContext (package:thingsboard_app/core/context/tb_context.dart:565:5)
I/flutter ( 6521):   ERROR │ ⛔ <asynchronous suspension>
I/flutter ( 6521):   ERROR │ ⛔ 
I/flutter ( 6521):   ERROR └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
![image](https://user-images.githubusercontent.com/17524912/187873845-d4b2defc-4de7-4ef4-943b-0ecbbf39b502.png)

How can I solve this problem？thanks!

**Comment by IoTThinks** [comment]
It works for my TB 3.3.4.1.
