### ISSUE TITLE
Cannot build APK

### ISSUE THREAD

**Issue by realbeeit** [thingsboard/flutter_thingsboard_app#33]
Hello everyone,
I am new to Android Studio but I managed it to make app work in emulator. However, I am unable to make APK. I got this message:

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s
Running Gradle task 'assembleRelease'...                           67,4s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1

**Comment by AscenX** [comment]
I got the same problem.Did you solve it?

**Comment by song-df** [comment]
Always failure with Resolving dependencies... (1.9s)
Because every version of flutter_localizations from sdk depends on intl 0.18.0 and thingsboard_app depends on intl
  ^0.17.0, flutter_localizations from sdk is forbidden.
So, because thingsboard_app depends on flutter_localizations from sdk, version solving failed. What can I do?

**Comment by ybeshkarov** [comment]
@song-df which version of Flutter do you use?

`flutter --version`
