### ISSUE TITLE
Issue in running the mobile app for the first time

### ISSUE THREAD

**Issue by JustinaMary** [thingsboard/flutter_thingsboard_app#34]
We are planning to use ThingsBoard’s open-source mobile application, to get the notification for the alarms and to view dashboards on the mobile devices. 

I have installed all the packages and software required for the TB flutter app to run on windows system, but the errors attached below got raised whenever I tried to run the app from VS code. 
Please investigate this and help us in resolving this issue. 

![image](https://user-images.githubusercontent.com/11269944/208380641-53c7a0e7-0783-4110-8c9f-985a81a9c52f.png)

**Comment by MM-06** [comment]
Did you use the thingsboard demo endpoint?

**Comment by DayDreamer-commits** [comment]
The app doesn't navigate after login.  Although I am getting the token and refresh token once the login API is completed.

I closed the app and reopened it but is gives following error

**Unsupported ThingsBoard platform version: 3.3.4.1**
The docs mentions that **Flutter ThingsBoard Mobile Application is served by ThingsBoard platform starting from version 3.3.0**. Any help to fix this would be appreciated. @JustinaMary Have you found any solution to this??

**Comment by DayDreamer-commits** [comment]
After debugging for few hours I realized that the thingsboard client library 1.0.4 needs minimum version  3.4.2. ThingsBoard website docs is valid for client version 1.0.1.

**Comment by MM-06** [comment]
@DayDreamer-com so does changing the thingsboard client version to 1.0.1 in the pubspec.yaml file solve the login issue?

**Comment by DayDreamer-commits** [comment]
No there are some breaking changes. I am trying it with some old commit.

**Comment by DayDreamer-commits** [comment]
By the way it would be better to update thingsboard server than trying the old commit.

**Comment by DayDreamer-commits** [comment]
With a previous commit (227c712d)and lots of changes finally its working.

**Comment by MM-06** [comment]
@DayDreamer-commits if you don't mind, could you please list the changes you made?

**Comment by DayDreamer-commits** [comment]
I haven't listed it but just get a branch from that commit and run it. resolve the errors one by one and after few steps it will work.

**Comment by MM-06** [comment]
@DayDreamer-commits I've been trying to resolve this issue on the PE edition, with your advice I've used an older commit and debugged. It works perfectly now, Thanks a lot for your help!!

**Comment by hieunvce** [comment]
I've the same issue. After upgrade TB to the latest version, it works now.
