### ISSUE TITLE
Why there is no generic cloud app?

### ISSUE THREAD

**Issue by Ifousoft** [thingsboard/flutter_thingsboard_app#36]
Dear maker
I found the generic app to access to demo dashboard.
But why is there not an app for cloud dashboard?
Have to put flutter dart Android studio avdtools... 
I used one day and at the end the login does... Nothing.

Could anyone exclaim me why I can't find a generic app for cloud thingsboard version?
Thanks!

**Comment by paolofrs** [comment]
@Ifousoft can you edit the title and correct genetic with generic... ? that might help other looking for this issue...

**Comment by Ifousoft** [comment]
Dear,

Thanks for your message. I have switched to mqtt with a local server on my
nas.

Have a nice day.

Le jeu. 20 avr. 2023 à 09:42, Paolo Fresch ***@***.***> a
écrit :
