### ISSUE TITLE
Flutter thingsboard mobile app no answer after login

### ISSUE THREAD

**Issue by Ifousoft** [thingsboard/flutter_thingsboard_app#37]
Hi!
After creating mobile app with Flutter and thingsboard, On the android 11 emulator, I obtained the login/password page.
I put my credentials for thingsboard.cloud and get... nothing.
The debug put no error messages.
I case I put wrong credentials, I got an error message.

Why can I access to my dashboards defined on thingsboard.cloud ?

Thanks!

**Comment by yunamoon** [comment]
Hi. I'm having a similar problem. In my case, I can't access the dashboard. Did you find a solution?

**Comment by vvlladd28** [comment]
Hi @Ifousoft and @yunamoon
We are very sorry that you received this error. We have already updated the code in the master branch and fixed this problem.

**Comment by vvlladd28** [comment]
You need to use another project (https://github.com/thingsboard/flutter_thingsboard_pe_app) to connect thingsboard.cloud
