### ISSUE TITLE
Unsupported version 

### ISSUE THREAD

**Issue by xlu103** [thingsboard/flutter_thingsboard_app#39]
I can not open the APP, stuck in the loading page, the error is not supported version.

flutter_thingsboard_app version last
thingsboard last

**Comment by wplarthshkr** [comment]
Hi, maybe I have the same problem. When I run the app, stuck in the loading page. I copy this error from debugger: 

⛔ Failed to init tbContext: ThingsboardError: message: [Unsupported ThingsBoard platform version: 3.5.1PAAS], errorCode: 2, status: null

Please if someone find the solution share it. Thanks.

**Comment by ellenfel** [comment]
> Hi, with thingsboard 3.5.0, you need to recompile the app with the new sources.
> 
> [thingsboard/flutter_thingsboard_pe_app#45](https://github.com/thingsboard/flutter_thingsboard_pe_app/issues/45)
> 
> Best regards

I am sorry but i am kinda new to mobile app part of thingsboard. Can you shortly explain what do you mean by "compiling with new sources".

**Comment by Xlu103** [comment]
> > Hi, with thingsboard 3.5.0, you need to recompile the app with the new sources.您好，使用 thingsboard 3.5.0，您需要使用新源重新编译应用程序。
> > [thingsboard/flutter_thingsboard_pe_app#45 事物板/flutter_thingsboard_pe_app#45](https:github.com/thingsboard/flutter_thingsboard_pe_app/issues/45)
> > Best regards Sincerely
>
> I am sorry but i am kinda new to mobile app part of thingsboard. Can you briefly explain what do you mean by "compiling with new sources". Can you briefly explain what you mean by "compile with new sources"?

Meaning probably, using the latest version of the code, re-run
