### ISSUE TITLE
In customer user mode, don't want to show all device profile in Devices list.

### ISSUE THREAD

**Issue by jiekechoo** [thingsboard/flutter_thingsboard_app#4]
![image](https://user-images.githubusercontent.com/3350211/129507037-0e60a990-3e64-4ef1-8e3c-cfe739473d7f.png)

As above pic, I don't want to show ALL device profile to customer user. If admin didn't assign device to user, I think should hide device profile.

**Comment by IoTThinks** [comment]
I think need to fix the SQL queries in the app?
Just curious. Would you mind showing a test Dashboard inside the mobile app? Thanks a lot.

**Comment by jiekechoo** [comment]
> I think need to fix the SQL queries in the app?
> Just curious. Would you mind showing a test Dashboard inside the mobile app? Thanks a lot.

I totally test the app in android platform, it seems OK.
I'll filter zero device profile in the app.
I don't want see a test Dashboard ,ha.
