### ISSUE TITLE
Not able to view dashboard using endpoint : https://demo.thingsboard.io

### ISSUE THREAD

**Issue by Anmirazik** [thingsboard/flutter_thingsboard_app#40]
the app keeps loading like this as shown below when I tried to open the dashboard 

![image](https://user-images.githubusercontent.com/113960675/236626557-ae921bed-b557-4bb4-b1f7-320592c03001.png)

the error on console shows , this is only some part , I cannot show all due to the error keeps adding up indefinitely 

![image](https://user-images.githubusercontent.com/113960675/236626577-181944ff-37b1-46ec-90cf-05aa0e24ae9f.png)

what happened ? I believe before this I'm using demo endpoint it works fine but now its not , is is related to the current thingsboard version which has been updated recently ?

**Comment by ezeroldan24** [comment]
I have the same problem with the new version of thingsboard. Using android 10 emulator, log in but it keeps loading and never starts the panel. Any solution?

**Comment by ezeroldan24** [comment]
![notfound](https://github.com/thingsboard/flutter_thingsboard_app/assets/91096768/06eb42c8-9072-4b16-8fef-49b5b09d1396)
I leave an image of what happens when the board doesn't work

**Comment by Anmirazik** [comment]
> ![sdk](https://user-images.githubusercontent.com/91096768/276691862-f444ec41-6df6-458f-8d05-c793ee454c0c.PNG)
> 
> ![host](https://user-images.githubusercontent.com/91096768/276692219-ce5a6144-b2e6-4114-ab35-3b3b73006aed.PNG)
> 
> We have our own host, I had already been using the app, everything was fine, but when they updated thingsboard.cloud the panels broke. At least for versions smaller than 12, it works on the android 12 emulator. SDK 33 as shown in the photo and flutter to the latest update. What catches my attention is that the app loads normally, the problem is only with the dashboards Thank you for your reply.

so you mean it works on android 12 emulator but not android 10 emulator right ? i believe we might need to wait for the developer because i have not tried to run the app on android 12 emulator and below . my issues is more on the whole dashboard are not able to render meanwhile yours seems like some of the components are not rendered however my issues was solved using the android 12 emulator and above .

**Comment by ezeroldan24** [comment]
Thank you for your help. If, on Android 12 it works, it should be an app compatibility issue. I'm going to see if the github of the thingsboard mobile app gives me any solution to the problem.
