### ISSUE TITLE
I am not able to setup in my mac M1 . I have flutter 3 version. Plzz help me. I am getting a lot of errors

### ISSUE THREAD

**Issue by amanat-2003** [thingsboard/flutter_thingsboard_app#43]
^
: Error: Required named parameter 'minScrollExtent' must be provided.
scroll_metrics.dart:202
    return FixedScrollMetrics(
                             ^
: Context: Found this candidate, but the arguments don't match.
scroll_metrics.dart:142
  FixedScrollMetrics({
  ^^^^^^^^^^^^^^^^^^
: Error: The method 'toMap' isn't defined for the class 'AxisDirection'.
scroll_metrics.dart:218
- 'AxisDirection' is from 'package:flutter/src/painting/basic_types.dart' ('../../../sdks/flutter/packages/flutter/lib/src/painting/basic_types.dart').
basic_types.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'toMap'.
      'axisDirection': axisDirection.toMap(),
                                     ^^^^^
: Error: Enums can't be instantiated.
scroll_metrics.dart:229
      axisDirection: AxisDirection.fromMap(map['axisDirection'] as Map<String,dynamic>),

                                   ^^^^^^^
: Error: Required named parameter 'minScrollExtent' must be provided.
scroll_metrics.dart:224
    return FixedScrollMetrics(
                             ^
: Context: Found this candidate, but the arguments don't match.
scroll_metrics.dart:142
  FixedScrollMetrics({

**Comment by ybeshkarov** [comment]
Hello @amanat-2003!

Please try with the latest `Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git`.
And don't forget to run the command`sudo softwareupdate --install-rosetta --agree-to-license` in your terminal according to Flutter documentation. 

All works well for me.
