### ISSUE TITLE
The dashboard does not load on the update

### ISSUE THREAD

**Issue by ezeroldan24** [thingsboard/flutter_thingsboard_app#45]
Good morning, as of the thingsboard.cloud update to version 3.6, you can enter but the panel keeps loading and never starts. Why is that?

**Comment by ezeroldan24** [comment]
Dashboard loading only works on Android 12, older versions keep loading and don't work. I have SDK 33, the latest version to make it compatible with everyone.

**Comment by fvob** [comment]
I have encountered the same problem, the reason why the dashboard continues to load is that the Android version is too low. My question is how to achieve support for most Android versions

**Comment by ezeroldan24** [comment]
> I have encountered the same problem, the reason why the dashboard continues to load is that the Android version is too low. My question is how to achieve support for most Android versions

How are you fvop? I still couldn't solve it, but I think it goes beyond what we change in the project dependencies, because I already tried many things. We should wait for some app developer to answer us.

**Comment by ezeroldan24** [comment]
@ikulikov Alguna respuesta a este enunciado?

**Comment by ezeroldan24** [comment]
@ikulikov

**Comment by ybeshkarov** [comment]
Hello @ezeroldan24!

I've tested on API level 30 and the dashboard works fine for me.

Could you confirm whether this issue still occurs with the latest master code?

**Comment by ybeshkarov** [comment]
Awesome, glad to hear it :)
