### ISSUE TITLE
APP is not working

### ISSUE THREAD

**Issue by vishal03121998** [thingsboard/flutter_thingsboard_app#47]
I am trying log in into mobile app but after building app when I tried to run app, app is just loading and not moving in into login page.If it goes to the login page it is not going logging in even after given correct username and password. If I give wrong username or password , it shows username or password is incorrect.

Thingboard Version 3.4.4 CE
Browser: Chrome or Firefox Latest
APP IDE: Android Studio

**Comment by QuakeString** [comment]
having same issue with me.

**Comment by ybeshkarov** [comment]
Hello @vishal03121998!

Could you please add more details about your environment? Like: Android/IOS, OS version, app version, etc.
