### ISSUE TITLE
Fatal application error ocurred: Unsupported Thingsboard version :3.6.1.3PASS

### ISSUE THREAD

**Issue by ezeroldan24** [thingsboard/flutter_thingsboard_app#51]
Good afternoon. I've been having this problem for a while now and I'm cloning the latest version of the app. Does anyone know how I can fix it? Thank you

![celu](https://github.com/thingsboard/flutter_thingsboard_app/assets/91096768/5ac82251-c22c-4ce2-adb0-a9306bc96d06)

**Comment by hayschan** [comment]
I can't even build the PE version of this app. Do you think this issue is related?

https://github.com/thingsboard/flutter_thingsboard_pe_app/issues/59

**Comment by hayschan** [comment]
Yep. This issue for this is that the version Thingsboard Cloud is 3.6.1.3.

Reference: [Flutter ThingsBoard PE Mobile Application compatibility table](https://thingsboard.io/docs/pe/mobile/getting-started/#step-2-get-app-source-code)

You should use `v1.0.8` of the PE mobile app.

ThingsBoard PE version | Flutter ThingsBoard PE Mobile Application | Dart ThingsBoard PE Client
-- | -- | --
3.6.2PE+ | 1.0.9 | 1.0.9
3.6.0PE+ | 1.0.8 | 1.0.8
3.5.0PE+ | 1.0.7 | 1.0.7
3.4.2PE+ | 1.0.5 | 1.0.5
3.4.0PE+ | 1.0.4 | 1.0.4

**Comment by owen63** [comment]
I have the same problem, connecting to ThingsBoard Cloud. I get Unsupported ThingsBoard platform version: 3.6.1.3PAAS regardless of whether I use release/1.0.7 or release/1.0.8 branch of flutter_thingsboard_app. Note that I am using ThingsBoard Mobile Application rather then ThingsBoard **PE** Mobile Application. Is this an issue / what's the difference?

**Comment by owen63** [comment]
ThingsBoard PE Mobile Application 1.0.8 fixed it.

**Comment by hayschan** [comment]
> I have the same problem, connecting to ThingsBoard Cloud. I get Unsupported ThingsBoard platform version: 3.6.1.3PAAS regardless of whether I use release/1.0.7 or release/1.0.8 branch of flutter_thingsboard_app. Note that I am using ThingsBoard Mobile Application rather then ThingsBoard **PE** Mobile Application. Is this an issue / what's the difference?

I used ThingsBoard PE Mobile Application `v1.0.8` and solves the problem.

The reason for the problem is that the version of Thingsboard Cloud is not yet updated to the latest version `v3.6.2PE+` by Thingsboard team. You can check my [reply](https://github.com/thingsboard/flutter_thingsboard_app/issues/51#issuecomment-1878505353) for the table.

**Comment by nikolamaksim1** [comment]
what's the difference between thingsboard mobile app and thingsboard pe mobile app?

**Comment by hayschan** [comment]
> what's the difference between thingsboard mobile app and thingsboard pe mobile app?

The former is for the community edition of Thingsboard. The latter is for the paid version of Thingsboard.

**Comment by chowardcode** [comment]
Has this issue rearisen since 3.6.2.2? I am getting  

Unsupported Thingsboard platform version: 3.6.2.2PAAS using newest repo for flutter tb PE.   Account type is cloud PE prototype

**Comment by ybeshkarov** [comment]
Hello, @chowardcode!

You will get this error only in the case if you try to connect to the PE backend from the CE source code.

**Comment by chetankumar-cms** [comment]
I am getting error while running **master branch** and connecting to[ https://demo.thingsboard.io]( https://demo.thingsboard.io)
Fatal application error ocurred:**Unsupported ThingsBoard platform version: 3.7.0.1DEMO**
Please advice how to fix ?

**Comment by Vaibhav0216** [comment]
@ezeroldan24 ,
How you solved your problem? I am facing same issue. 

Fatal application error occurred: unsupported Thingsboard platform version: 3.8.1.7PASS

ThingsBoard PE version :  3.8.1.7
Flutter ThingsBoard PE Mobile Application: 1.4.0
Dart ThingsBoard PE Client: ^2.0.0

I didn't understand how to resolve this issue.

**Comment by ThinLizzy13** [comment]
> @ezeroldan24 , How you solved your problem? I am facing same issue.
> 
> Fatal application error occurred: unsupported Thingsboard platform version: 3.8.1.7PASS
> 
> ThingsBoard PE version : 3.8.1.7 Flutter ThingsBoard PE Mobile Application: 1.4.0 Dart ThingsBoard PE Client: ^2.0.0
> 
> I didn't understand how to resolve this issue.

same
