### ISSUE TITLE
The dashboard does not load in web app!

### ISSUE THREAD

**Issue by hl1369** [thingsboard/flutter_thingsboard_app#53]
Hello every body,

i tried to build web app by this mobile application,
dashboards load in android but don't load in web app!
in dashboard just write: Not implemented!

do you know any solutions? (I tried with version 3.61 and 3.6.2 CE. and mobile app version 1.0.6 and 1.0.8 and result was the same like below image)
![tb-webapp](https://github.com/thingsboard/flutter_thingsboard_app/assets/130842131/afa7f5b6-da80-45d1-af1a-c18bc553d1f7)

**Comment by ybeshkarov** [comment]
Hello, @hl1369!
Thanks for reaching us.

It's expected behavior and not an issue.

**Comment by peilinhu** [comment]
Hello, I have also encountered this problem. Is this a setting issue? How can I correctly display the dashboard?

**Comment by peilinhu** [comment]
> Hello, [@hl1369](https://github.com/hl1369)! Thanks for reaching us.
> 
> It's expected behavior and not an issue.

Hello, I have also encountered this problem, Is this a setting issue? How can I correctly display the dashboard?
