### ISSUE TITLE
iOS: If home dashboard is selected, home page loads forever

### ISSUE THREAD

**Issue by qoentz** [thingsboard/flutter_thingsboard_app#54]
Using the latest version, 1.0.8, if the account you sign into on a iOS device has a selected home dashboard under account the the page loads forever  on first login like this:
![IMG_0015](https://github.com/thingsboard/flutter_thingsboard_app/assets/93362730/afd72d6f-20f1-4f90-8e1c-65c549644ada)

I have tested this on my own server as well as my own app, then I have tried a clean version of the app from this repo following this guide: https://thingsboard.io/docs/mobile/getting-started/
I have tried my own server as well as demo.thingsboard.io but non of them work if I have a selected home dashboard.

**Comment by qoentz** [comment]
i am not sure what causes it

**Comment by ybeshkarov** [comment]
Hello @qoentz!

Please try to change the endpoint to [as mentioned in Step 3](https://thingsboard.io/docs/mobile/getting-started/) and try again. 
I'm not able to get loads forever.
