### ISSUE TITLE
The app only loads the panels with the demo address, it doesn't load with my local installation.

### ISSUE THREAD

**Issue by Hkeoke** [thingsboard/flutter_thingsboard_app#67]

**Comment by Hkeoke** [comment]
The app only loads the panels with the demo address, it doesn't load with my local installation

**Comment by ybeshkarov** [comment]
Hi @Hkeoke!

Consider adding dashboards to your local installation.
<img width="1728" alt="Screenshot 2024-04-03 at 15 05 48" src="https://github.com/thingsboard/flutter_thingsboard_app/assets/10604455/ef3a60d1-07ec-43ad-8e1c-9817803df522">
