### ISSUE TITLE
Access to originator of notification

### ISSUE THREAD

**Issue by mahshadparsa** [thingsboard/flutter_thingsboard_app#69]
Hi every one 
I try to get the originator of the notification. When I print ('[WebSocket Data]: Received notification: ${notification.notifications}');
I can see the originator. But when I try to access it by ‘notification.notifications?.first’. , I can't get any originator suggestions but other parts exist.
This problem is shown at below :
![Untitled](https://github.com/thingsboard/flutter_thingsboard_app/assets/13507162/11690607-35cc-4890-aee0-47743b94b6bd)

Please guide me on how I can access to originator of notification.

**Comment by ybeshkarov** [comment]
Hi @mahshadparsa!

Could you please add a print output for` print ('[WebSocket Data]: Received notification: ${notification.notifications}');`? Also, mark the field you are interested in.
