### ISSUE TITLE
Editing a Dashboard's Time Window inaccessible on release 1.0.8

### ISSUE THREAD

**Issue by torrswanson** [thingsboard/flutter_thingsboard_app#83]
# Issue:
When editing a time window in a dashboard, the rendered view is not responsive and is off the visible screen.

# Expect:
I expect the time window to be within the bounds of the screen

# Work-around:
Unknown

# Screenshots:
![Screenshot 2024-04-26 at 12 47 34 copy](https://github.com/thingsboard/flutter_thingsboard_app/assets/13242557/f33c4bba-2bd1-42d6-a381-0af995baed93)

# Versions:
Flutter 1.0.8
Thingsboard v3.6.2
iPhone SE Generation 2 running iOS 17.4.1

**Comment by WillieSpence** [comment]
Same here. Seems to only affect iOS devices.

**Comment by ybeshkarov** [comment]
Hello @torrswanson,

This is an issue with the web component on the platform rather than mobile. So we need to wait when a platform will fix it.
There is a corresponding link https://github.com/thingsboard/thingsboard/issues/8795
