### ISSUE TITLE
Flutter SDK version

### ISSUE THREAD

**Issue by thebadking** [thingsboard/flutter_thingsboard_app#85]
I am having troubles starting this project, initially I tested with the latest flutter version  (3.22.0) immediately had dependency errors, then I went down to (3.16.9) and it ran further but had:
```
Running Gradle task 'assembleDebug'...                            
lib/utils/services/widget_action_handler.dart:290:29: Error: The argument type 'List<int>?' can't be assigned to the parameter type 'List<int>' because 'List<int>?' is nullable and 'List<int>' isn't.
```
Android SDK Platform 32 (revision: 1)

and the latest version of Android Studio

Can someone advise on the dependencies versions? thanks

**Comment by ybeshkarov** [comment]
Hello @thebadking!

Did you change any dependency versions in `pubspec.yaml`? Generally, this error indicates that you're trying to assign a nullable type to a non-nullable one. To fix it, consider making `List<int>` nullable.

**Comment by thebadking** [comment]
@ybeshkarov  Thank you for pointing it out, I didn't change anything but just for safe measure  I did reset the repo and also chose a different android image and now it works, I was able to run the app, how do I go about testing it? which back end should I run and how do I point the app to it?

**Comment by ybeshkarov** [comment]
With this CE repository you can use https://demo.thingsboard.io/. For more information on getting started, visit https://thingsboard.io/docs/mobile/getting-started/.

@thebadking

**Comment by escalanterj** [comment]
Hello, I get the following error, any clue?
Because every version of flutter_localizations from sdk depends on intl 0.19.0 and thingsboard_app depends on intl 0.18.0, flutter_localizations from sdk is forbidden.
So, because thingsboard_app depends on flutter_localizations from sdk, version solving failed.


Thanks!!
