### ISSUE TITLE
2FA and notifications broken

### ISSUE THREAD

**Issue by Philip2809** [thingsboard/flutter_thingsboard_app#92]
If you have 2FA enabled and login to newest version on app, tried on (thingsboard demo app), you will get a 403 when the app is trying to setup notifications, this gives a red banner at bottom saying "You don't have permission to preform this operation!". This is because when you have 2FA you only have access to 2FA endpoint to put in the code before you get your full jwt access token, but the app tries to setup notifications before the 2FA auth is completed.

**Comment by ybeshkarov** [comment]
Duplicate https://github.com/thingsboard/flutter_thingsboard_app/issues/25

**Comment by Philip2809** [comment]
Its not really a duplicate @ybeshkarov, last problem was before the notification update, and that was stating problems with logging in, this however, you can login but not all functions will work!

**Comment by ybeshkarov** [comment]
Hello @Philip2809,

I've considered it as a duplicate because it's a login issue when 2FA is enabled. The behavior has changed, but the issue was.
But anyway thanks for your reporting. This will be fixed in the 1.2.0 release soon.

**Comment by Philip2809** [comment]
Awesome, is 1.2.0 coming with 3.7? Any planned date for release?

**Comment by ybeshkarov** [comment]
Correct. About the planned date not sure but must be soon.
