### ISSUE TITLE
Problems with the dart thingsboard client library 

### ISSUE THREAD

**Issue by Yellowfantt** [thingsboard/flutter_thingsboard_app#93]
I'm working on a mobile application with the thingsboard community version, I implemented the "thingsboard_client: ^1.1.1" library and when I authenticate using it, I'm getting the following problem:
<img width="736" alt="problema" src="https://github.com/thingsboard/flutter_thingsboard_app/assets/54282309/e5d6b4d9-dc52-49c4-8029-a58185fb7bc0">
I also tried changing the library version, but the problem continues to persist, has anyone experienced this and could help me?

<img width="529" alt="saveee" src="https://github.com/thingsboard/flutter_thingsboard_app/assets/54282309/9dbcdc64-daad-4540-8bd2-01888ceb2572">

**Comment by ybeshkarov** [comment]
Hello @Yellowfantt,

we will release a new version of the thingsboard_client soon and this issue will be fixed there.
Hope it works for you.

**Comment by Yellowfantt** [comment]
> Olá@Yellowfantt,
> 
> lançaremos uma nova versão do thingsboard_client em breve e esse problema será corrigido lá. Espero que funcione para você.

Ok. Thanks for the feedback!

**Comment by ybeshkarov** [comment]
Hi @Yellowfantt,
The 1.2.0 version of the `thingsboard_client` was published. The issue you described is fixed there.
