### ISSUE TITLE
Sorry,how to let the app to support version 3.7.0

### ISSUE THREAD

**Issue by haisom2022** [thingsboard/flutter_thingsboard_app#94]
<img width="335" alt="image" src="https://github.com/thingsboard/flutter_thingsboard_app/assets/103404415/fce9aede-8d5a-4c85-b8a0-7cb97e073127">

**Comment by ybeshkarov** [comment]
Using thingsboard_client: ^1.2.0 should resolve it.
@haisom2022

**Comment by salemaljebaly** [comment]
> Using thingsboard_client: ^1.2.0 should resolve it. @haisom2022

Thanks for your efforts

I test latest version of thingsboard_client but its still same error
also I test dev branch in flutter_thingsboard_app to get latest update and fixes in code but same error occurs.

I monitoring the app network using flutter dev tools the login works correctly and it return token and refresh token 
the same error occur Unsupported ThingsBoard platform version: 3.7.0-
SNAPSHOT

**Comment by ybeshkarov** [comment]
@salemaljebaly  Are you using http://demo.thingsboard.io?

**Comment by salemaljebaly** [comment]
> @salemaljebaly Are you using https://demo.thingsboard.io?

Its working on https://demo.thingsboard.io/
but I try to run it in my own server with thingsboard CE

**Comment by BigNavid** [comment]
Same problem when using my own server with thingsboard CE version 3.6.4
![Screenshot_20240617_145939](https://github.com/thingsboard/flutter_thingsboard_app/assets/7349105/f864c2db-76e5-41ea-b775-903cab410be3)

**Comment by ybeshkarov** [comment]
I see, thanks.

The issue has been resolved in thingsboard_client: ^1.2.1. Please update your pubspec.yaml as necessary.

@BigNavid, @salemaljebaly, @haisom2022
